name: Tests

on:
  push:
  pull_request:
  workflow_dispatch: # Allow manual triggering

jobs:
  test-scripts:
    name: Test Scripts
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test scripts
      run: |
        ./scripts/tests/run_tests.sh
